---
env:
  global:
    - CC_TEST_REPORTER_ID=ca253e335641a2bf3e6d69d8325242bb2d70cd0f282fbe48c77a729e0299acbe
language: node_js
node_js:
  - stable
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make lint test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
